### ISSUE TITLE
PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by xingfanxia** [allenfrostline/pyNCMDUMP#10]
```
❯ python3 ncmdump.py test.ncm                                                                                                                                                                      ─╯
   INFO [2023-03-16 02:55:51]
   INFO [2023-03-16 02:55:51]            _  _  ___ __  __ ___  _   _ __  __ ___
   INFO [2023-03-16 02:55:51]  _ __ _  _| \| |/ __|  \/  |   \| | | |  \/  | _ \
   INFO [2023-03-16 02:55:51] | '_ \ || | .` | (__| |\/| | |) | |_| | |\/| |  _/
   INFO [2023-03-16 02:55:51] | .__/\_, |_|\_|\___|_|  |_|___/ \___/|_|  |_|_|
   INFO [2023-03-16 02:55:51] |_|   |__/
   INFO [2023-03-16 02:55:51]                     pyNCMDUMP
   INFO [2023-03-16 02:55:51]     https://github.com/allenfrostline/pyNCMDUMP
   INFO [2023-03-16 02:55:51]
   INFO [2023-03-16 02:55:51] Running pyNCMDUMP on single-worker mode
   INFO [2023-03-16 02:55:51] Converting "test.ncm"
Traceback (most recent call last):
  File "/Users/xingfanxia/projects/pyNCMDUMP/ncmdump.py", line 181, in <module>
    dump(*args.paths, n_workers=args.workers)
  File "/Users/xingfanxia/projects/pyNCMDUMP/ncmdump.py", line 158, in dump
    for fp in tqdm(all_filepaths, leave=False): dump_single_file(fp)
  File "/Users/xingfanxia/projects/pyNCMDUMP/ncmdump.py", line 71, in dump_single_file
    cryptor = AES.new(core_key, AES.MODE_ECB)
  File "/opt/homebrew/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```
Maybe a non compatible version of pycrypto

**Comment by xingfanxia** [comment]
This is an issue in py 3.10, can be fixed by installing
```
pip uninstall pycrypto
pip install pycryptodome
```

**Comment by xingfanxia** [comment]
On 3.10 any module(s) that use the # variant when parsing arguments need to have a #define PY_SSIZE_T_CLEAN before including Python.h.
